{{- if .Values.objectStore.enabled }}
{{- $name := include "cnpg-cluster.fullname" . }}
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: {{ $name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cnpg-cluster.labels" . | nindent 4 }}
spec:
  {{- toYaml (omit .Values.objectStore "enabled") | nindent 2 }}
{{- end }}
