{{- define "cnpg-cluster.netpol.cluster-primary" -}}
{{- $name := include "cnpg-cluster.fullname" . -}}
endpointSelector:
  matchLabels:
    cnpg.io/cluster: {{ $name }}
    cnpg.io/instanceRole: primary
egress:
  - toEndpoints:
      - matchLabels:
          cnpg.io/cluster: {{ $name }}
          cnpg.io/instanceRole: replica
    toPorts:
      - ports:
          - port: "8000"
            protocol: TCP
ingress:
  - fromEndpoints:
      - matchLabels:
          cnpg.io/cluster: {{ $name }}
          cnpg.io/jobRole: join
      - matchLabels:
          cnpg.io/cluster: {{ $name }}
          cnpg.io/instanceRole: replica
    toPorts:
      - ports:
          - port: "5432"
            protocol: TCP
{{- end -}}
{{- include "templates.ciliumNetworkPolicy" (dict
  "root" $
  "name" (printf "%s-cnpg-cluster-primary" (include "cnpg-cluster.fullname" .))
  "value" (include "cnpg-cluster.netpol.cluster-primary" . | fromYaml)
) }}
