{{- define "cnpg-cluster.netpol.cluster-replica" -}}
{{- $name := include "cnpg-cluster.fullname" . -}}
endpointSelector:
  matchLabels:
    cnpg.io/cluster: {{ $name }}
    cnpg.io/instanceRole: replica
egress:
  - toEndpoints:
      - matchLabels:
          cnpg.io/cluster: {{ $name }}
          cnpg.io/instanceRole: primary
    toPorts:
      - ports:
          - port: "5432"
            protocol: TCP
ingress:
  - fromEndpoints:
      - matchLabels:
          cnpg.io/cluster: {{ $name }}
          cnpg.io/instanceRole: primary
    toPorts:
      - ports:
          - port: "8000"
            protocol: TCP
{{- end -}}
{{- include "templates.ciliumNetworkPolicy" (dict
  "root" $
  "name" (printf "%s-cnpg-cluster-replica" (include "cnpg-cluster.fullname" .))
  "value" (include "cnpg-cluster.netpol.cluster-replica" . | fromYaml)
) }}
