{{- $name := include "cnpg-cluster.fullname" . }}
{{- $metadata := (include "cnpg-cluster.metadata" (dict "root" $ "metadata" (default dict .Values.metadata) "name" $name) | fromYaml) }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ $metadata.name | quote }}
  namespace: {{ $metadata.namespace | quote }}
  labels:
    {{- toYaml $metadata.labels | nindent 4 }}
  {{- with $metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  instances: {{ .Values.instances }}

  {{- with .Values.imageName }}
  imageName: {{ . | quote }}
  {{- end }}
  {{- if .Values.imageCatalogRef.name }}
  imageCatalogRef:
    {{- toYaml .Values.imageCatalogRef | nindent 4 }}
  {{- end }}
  {{- if ne .Values.imagePullPolicy "IfNotPresent" }}
  imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
  {{- end }}
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  storage:
    size: {{ .Values.storage.size | quote }}
    {{- with .Values.storage.storageClass }}
    storageClass: {{ . | quote }}
    {{- end }}
    {{- with .Values.storage.pvcTemplate }}
    pvcTemplate:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- if .Values.walStorage.enabled }}
  walStorage:
    size: {{ .Values.walStorage.size | quote }}
    {{- with .Values.walStorage.storageClass }}
    storageClass: {{ . | quote }}
    {{- end }}
  {{- end }}
  {{- with .Values.ephemeralVolumesSizeLimit }}
  ephemeralVolumesSizeLimit:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.postgresql }}
  postgresql:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- include "cnpg.bootstrap" . | nindent 2 }}
  {{- include "cnpg.backup" . | nindent 2 }}
  {{- include "cnpg.plugins" . | nindent 2 }}
  {{- include "cnpg.managed" . | nindent 2 }}

  {{- with .Values.externalClusters }}
  externalClusters:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.replica }}
  replica:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.replicationSlots }}
  replicationSlots:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if .Values.enableSuperuserAccess }}
  enableSuperuserAccess: true
  {{- end }}
  {{- if .Values.superuserSecret }}
  superuserSecret:
    name: {{ .Values.superuserSecret | quote }}
  {{- end }}

  {{- /* Resources */}}
  {{- with .Values.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- /* Scheduling */}}
  {{- with .Values.priorityClassName }}
  priorityClassName: {{ . | quote }}
  {{- end }}
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.topologySpreadConstraints }}
  topologySpreadConstraints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- include "cnpg.monitoring" . | nindent 2 }}

  {{- with .Values.env }}
  env:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.envFrom }}
  envFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if ne .Values.primaryUpdateMethod "restart" }}
  primaryUpdateMethod: {{ .Values.primaryUpdateMethod }}
  {{- end }}
  {{- if ne .Values.primaryUpdateStrategy "unsupervised" }}
  primaryUpdateStrategy: {{ .Values.primaryUpdateStrategy }}
  {{- end }}

  {{- if kindIs "invalid" .Values.enablePDB }}
    {{- if eq (int .Values.instances) 1 }}
  enablePDB: false
    {{- end }}
  {{- else }}
  enablePDB: {{ .Values.enablePDB }}
  {{- end }}

  {{- with .Values.clusterSpec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
