{{- $clusterName := include "cnpg-cluster.fullname" . }}
{{- $root := . }}
{{- range .Values.poolers }}
{{- if ne .enabled false }}
{{- $poolerSpec := omit . "name" "enabled" }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: {{ printf "%s-%s" $clusterName .name | quote }}
  namespace: {{ $root.Release.Namespace | quote }}
  labels:
    {{- include "cnpg-cluster.labels" $root | nindent 4 }}
spec:
  cluster:
    name: {{ $clusterName | quote }}
  {{- toYaml $poolerSpec | nindent 2 }}
{{- end }}
{{- end }}
