{{- include "cnpg-cluster.validate.instances" . }}
{{- include "cnpg-cluster.validate.image" . }}
{{- include "cnpg-cluster.validate.bootstrap" . }}
{{- include "cnpg-cluster.validate.objectStore" . }}
