imageName: ghcr.io/cloudnative-pg/postgresql:16.6
instances: 1
storage:
  size: 1Gi

objectStore:
  enabled: true
  configuration:
    destinationPath: s3://my-bucket/
    endpointURL: https://minio.example.com
    s3Credentials:
      accessKeyId:
        name: aws-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: aws-creds
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip

backup:
  enabled: false
  scheduledBackups:
    - name: daily
      schedule: "0 0 3 * * *"
      backupOwnerReference: self
      method: plugin
      pluginConfiguration:
        name: barman-cloud.cloudnative-pg.io
